// Generated by `wit-bindgen` 0.40.0. DO NOT EDIT!
#include "mod_world.h"
#include <stdlib.h>
#include <string.h>

// Imported Functions from `spaghettikart:module/iactor`

__attribute__((__import_module__("spaghettikart:module/iactor"), __import_name__("[constructor]actor")))
extern int32_t __wasm_import_spaghettikart_module_iactor_constructor_actor(uint8_t *, size_t, uint8_t *, size_t);

__attribute__((__import_module__("spaghettikart:module/iactor"), __import_name__("[method]actor.outside-init")))
extern void __wasm_import_spaghettikart_module_iactor_method_actor_outside_init(int32_t, float, float);

__attribute__((__import_module__("spaghettikart:module/iactor"), __import_name__("[method]actor.update")))
extern void __wasm_import_spaghettikart_module_iactor_method_actor_update(int32_t);

__attribute__((__import_module__("spaghettikart:module/iactor"), __import_name__("[method]actor.render")))
extern void __wasm_import_spaghettikart_module_iactor_method_actor_render(int32_t);

__attribute__((__import_module__("spaghettikart:module/iactor"), __import_name__("[method]actor.get-mod-id")))
extern void __wasm_import_spaghettikart_module_iactor_method_actor_get_mod_id(int32_t, uint8_t *);

__attribute__((__import_module__("spaghettikart:module/iactor"), __import_name__("[method]actor.get-id")))
extern void __wasm_import_spaghettikart_module_iactor_method_actor_get_id(int32_t, uint8_t *);

__attribute__((__import_module__("spaghettikart:module/iactor"), __import_name__("[method]actor.get-x")))
extern float __wasm_import_spaghettikart_module_iactor_method_actor_get_x(int32_t);

__attribute__((__import_module__("spaghettikart:module/iactor"), __import_name__("[method]actor.set-x")))
extern void __wasm_import_spaghettikart_module_iactor_method_actor_set_x(int32_t, float);

__attribute__((__import_module__("spaghettikart:module/iactor"), __import_name__("[method]actor.get-y")))
extern float __wasm_import_spaghettikart_module_iactor_method_actor_get_y(int32_t);

__attribute__((__import_module__("spaghettikart:module/iactor"), __import_name__("[method]actor.set-y")))
extern void __wasm_import_spaghettikart_module_iactor_method_actor_set_y(int32_t, float);

// Imported Functions from `mod-world`

__attribute__((__import_module__("$root"), __import_name__("init-actor")))
extern void __wasm_import_mod_world_init_actor(int32_t);

// Exported Functions from `mod-world`





// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Helper Functions

__attribute__((__import_module__("spaghettikart:module/iactor"), __import_name__("[resource-drop]actor")))
extern void __wasm_import_spaghettikart_module_iactor_actor_drop(int32_t handle);

void spaghettikart_module_iactor_actor_drop_own(spaghettikart_module_iactor_own_actor_t handle) {
  __wasm_import_spaghettikart_module_iactor_actor_drop(handle.__handle);
}

spaghettikart_module_iactor_borrow_actor_t spaghettikart_module_iactor_borrow_actor(spaghettikart_module_iactor_own_actor_t arg) {
  return (spaghettikart_module_iactor_borrow_actor_t) { arg.__handle };
}

void mod_world_string_set(mod_world_string_t *ret, const char*s) {
  ret->ptr = (uint8_t*) s;
  ret->len = strlen(s);
}

void mod_world_string_dup(mod_world_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void mod_world_string_free(mod_world_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

spaghettikart_module_iactor_own_actor_t spaghettikart_module_iactor_constructor_actor(mod_world_string_t *mod_id, mod_world_string_t *id) {
  int32_t ret = __wasm_import_spaghettikart_module_iactor_constructor_actor((uint8_t *) (*mod_id).ptr, (*mod_id).len, (uint8_t *) (*id).ptr, (*id).len);
  return (spaghettikart_module_iactor_own_actor_t) { ret };
}

void spaghettikart_module_iactor_method_actor_outside_init(spaghettikart_module_iactor_borrow_actor_t self, float x, float y) {
  __wasm_import_spaghettikart_module_iactor_method_actor_outside_init((self).__handle, x, y);
}

void spaghettikart_module_iactor_method_actor_update(spaghettikart_module_iactor_borrow_actor_t self) {
  __wasm_import_spaghettikart_module_iactor_method_actor_update((self).__handle);
}

void spaghettikart_module_iactor_method_actor_render(spaghettikart_module_iactor_borrow_actor_t self) {
  __wasm_import_spaghettikart_module_iactor_method_actor_render((self).__handle);
}

void spaghettikart_module_iactor_method_actor_get_mod_id(spaghettikart_module_iactor_borrow_actor_t self, mod_world_string_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_spaghettikart_module_iactor_method_actor_get_mod_id((self).__handle, ptr);
  *ret = (mod_world_string_t) { (uint8_t*)(*((uint8_t **) (ptr + 0))), (*((size_t*) (ptr + 4))) };
}

void spaghettikart_module_iactor_method_actor_get_id(spaghettikart_module_iactor_borrow_actor_t self, mod_world_string_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_spaghettikart_module_iactor_method_actor_get_id((self).__handle, ptr);
  *ret = (mod_world_string_t) { (uint8_t*)(*((uint8_t **) (ptr + 0))), (*((size_t*) (ptr + 4))) };
}

float spaghettikart_module_iactor_method_actor_get_x(spaghettikart_module_iactor_borrow_actor_t self) {
  float ret = __wasm_import_spaghettikart_module_iactor_method_actor_get_x((self).__handle);
  return ret;
}

void spaghettikart_module_iactor_method_actor_set_x(spaghettikart_module_iactor_borrow_actor_t self, float x) {
  __wasm_import_spaghettikart_module_iactor_method_actor_set_x((self).__handle, x);
}

float spaghettikart_module_iactor_method_actor_get_y(spaghettikart_module_iactor_borrow_actor_t self) {
  float ret = __wasm_import_spaghettikart_module_iactor_method_actor_get_y((self).__handle);
  return ret;
}

void spaghettikart_module_iactor_method_actor_set_y(spaghettikart_module_iactor_borrow_actor_t self, float y) {
  __wasm_import_spaghettikart_module_iactor_method_actor_set_y((self).__handle, y);
}

void mod_world_init_actor(mod_world_borrow_actor_t a) {
  __wasm_import_mod_world_init_actor((a).__handle);
}

__attribute__((__export_name__("init")))
void __wasm_export_exports_mod_world_init(void) {
  exports_mod_world_init();
}

__attribute__((__export_name__("actor-init")))
void __wasm_export_exports_mod_world_actor_init(int32_t arg, float arg0, float arg1) {
  exports_mod_world_actor_init((mod_world_borrow_actor_t) { arg }, arg0, arg1);
}

__attribute__((__export_name__("actor-update")))
void __wasm_export_exports_mod_world_actor_update(int32_t arg) {
  exports_mod_world_actor_update((mod_world_borrow_actor_t) { arg });
}

__attribute__((__export_name__("actor-render")))
void __wasm_export_exports_mod_world_actor_render(int32_t arg) {
  exports_mod_world_actor_render((mod_world_borrow_actor_t) { arg });
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_mod_world(void);
void __component_type_object_force_link_mod_world_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_mod_world();
}
