// Generated by `wit-bindgen` 0.40.0. DO NOT EDIT!
#ifndef __BINDINGS_MOD_WORLD_H
#define __BINDINGS_MOD_WORLD_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct mod_world_string_t {
  uint8_t*ptr;
  size_t len;
} mod_world_string_t;

typedef struct spaghettikart_module_iactor_own_actor_t {
  int32_t __handle;
} spaghettikart_module_iactor_own_actor_t;

typedef struct spaghettikart_module_iactor_borrow_actor_t {
  int32_t __handle;
} spaghettikart_module_iactor_borrow_actor_t;

typedef spaghettikart_module_iactor_borrow_actor_t mod_world_borrow_actor_t;

// Imported Functions from `spaghettikart:module/iactor`
extern spaghettikart_module_iactor_own_actor_t spaghettikart_module_iactor_constructor_actor(mod_world_string_t *mod_id, mod_world_string_t *id);
extern void spaghettikart_module_iactor_method_actor_outside_init(spaghettikart_module_iactor_borrow_actor_t self, float x, float y);
extern void spaghettikart_module_iactor_method_actor_update(spaghettikart_module_iactor_borrow_actor_t self);
extern void spaghettikart_module_iactor_method_actor_render(spaghettikart_module_iactor_borrow_actor_t self);
// getter/setter
extern void spaghettikart_module_iactor_method_actor_get_mod_id(spaghettikart_module_iactor_borrow_actor_t self, mod_world_string_t *ret);
extern void spaghettikart_module_iactor_method_actor_get_id(spaghettikart_module_iactor_borrow_actor_t self, mod_world_string_t *ret);
extern float spaghettikart_module_iactor_method_actor_get_x(spaghettikart_module_iactor_borrow_actor_t self);
extern void spaghettikart_module_iactor_method_actor_set_x(spaghettikart_module_iactor_borrow_actor_t self, float x);
extern float spaghettikart_module_iactor_method_actor_get_y(spaghettikart_module_iactor_borrow_actor_t self);
extern void spaghettikart_module_iactor_method_actor_set_y(spaghettikart_module_iactor_borrow_actor_t self, float y);

// Imported Functions from `mod-world`
extern void mod_world_init_actor(mod_world_borrow_actor_t a);

// Exported Functions from `mod-world`
void exports_mod_world_init(void);
void exports_mod_world_actor_init(mod_world_borrow_actor_t a, float x, float y);
void exports_mod_world_actor_update(mod_world_borrow_actor_t a);
void exports_mod_world_actor_render(mod_world_borrow_actor_t a);

// Helper Functions

extern void spaghettikart_module_iactor_actor_drop_own(spaghettikart_module_iactor_own_actor_t handle);

extern spaghettikart_module_iactor_borrow_actor_t spaghettikart_module_iactor_borrow_actor(spaghettikart_module_iactor_own_actor_t handle);

// Transfers ownership of `s` into the string `ret`
void mod_world_string_set(mod_world_string_t *ret, const char*s);

// Creates a copy of the input nul-terminate string `s` and
// stores it into the component model string `ret`.
void mod_world_string_dup(mod_world_string_t *ret, const char*s);

// Deallocates the string pointed to by `ret`, deallocating
// the memory behind the string.
void mod_world_string_free(mod_world_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
