package component:rust-component;

world example {
    record customer {
        id: u64,
        name: string,
    }

    export add: func(x: s32, y: s32) -> s32;
    export test: func() -> customer;
}
