package component:rust-component;

world example {
    export init: func();

    record actor {
        mod-id: string,
        id: string,
        x: f32,
        y: f32,
    }

    import init-actor: func(a: actor);
    export actor-init: func(a: actor)->bool;
    export actor-update: func(a: actor)->bool;
    export actor-render: func(a: actor)->bool;
}
